config/routes.rb
Rails.application.routes.draw do
  resources :countries
  resources :ips
  get "/" => "ips#stats"
  post "/masscreate" => "ips#masscreate"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/ip.rb
class Ip < ApplicationRecord
  @ip_regex = /^([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(\.([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])){3}$/
  validates :ip, 
            :presence => true, 
            :uniqueness => true,
            :format => { :with => @ip_regex,:multiline => true } 

end

def isip (ip) 
  ret = false
  if ip =~ /^([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(\.([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])){3}$/
    ret = true
  end
    return ret
end

def makecountry (ip)
        uri = URI("http://freegeoip.net/json/#{ip}")
        req = Net::HTTP.get(uri)
        dta = JSON.parse(req)
        co = Country.find_by name:dta["country_name"]
        if co.nil? 
          Country.create :name=>dta["country_name"]
          logger.debug "add country #{dta["country_name"]}"
          co = Country.find_by name:dta["country_name"]
        end
        mip = Ip.find_by ip:ip
        mip.update(:country => co.id)
        return nil
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name)
    end
end

app/controllers/ips_controller.rb
class IpsController < ApplicationController
  before_action :set_ip, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token # может я чего - то не понимаю, но стековерфлов говорит делать так

  # GET /ips
  # GET /ips.json
  def index
    @ips = Ip.all
  end

  # GET /ips/1
  # GET /ips/1.json
  def show
  end

  # GET /ips/new
  def new
    @ip = Ip.new
  end

  # GET /ips/1/edito
  def edit
  end

  # POST /ips
  # POST /ips.json
  def create
    @ip = Ip.new(ip_params)

    respond_to do |format|
      if @ip.save
        format.html { redirect_to @ip, notice: 'Ip was successfully created.' }
        format.json { render :show, status: :created, location: @ip }
        makecountry(@ip.ip)
      else
        format.html { render :new }
        format.json { render json: @ip.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /ips/1
  # PATCH/PUT /ips/1.json
  def stats 
    @stat = ActiveRecord::Base.connection.execute("select c.name as country ,count(ip.id) as cnt from countries c 
      left join ips ip on ip.country = c.id 
      group by c.id")
    render :stat , stat: @stat
    
  end

  def masscreate
    post_params = JSON.parse(request.body.read)
    logger.debug post_params
    post_params.each {|a| 
      if isip(a["ip"])
        Ip.create(ip: a["ip"])
        makecountry(a["ip"])
      end
    }
    render json: { "a": 42}
  end

  def update
    respond_to do |format|
      if @ip.update(ip_params)
        format.html { redirect_to @ip, notice: 'Ip was successfully updated.' }
        format.json { render :show, status: :ok, location: @ip }
        makecountry(@ip.ip)
        

      else
        format.html { render :edit }
        format.json { render json: @ip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ips/1
  # DELETE /ips/1.json
  def destroy
    @ip.destroy
    respond_to do |format|
      format.html { redirect_to ips_url, notice: 'Ip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ip
      @ip = Ip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ip_params
      params.require(:ip).permit(:ip, :country)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/ips_helper.rb
module IpsHelper
end

app/views/countries/_form.html.erb
<%= form_for(country) do |f| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Countries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Country', new_country_path %>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>

app/views/ips/_form.html.erb
<%= form_for(ip) do |f| %>
  <% if ip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ip.errors.count, "error") %> prohibited this ip from being saved:</h2>

      <ul>
      <% ip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ip %>
    <%= f.text_field :ip %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/ips/edit.html.erb
<h1>Editing Ip</h1>

<%= render 'form', ip: @ip %>

<%= link_to 'Show', @ip %> |
<%= link_to 'Back', ips_path %>

app/views/ips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ips</h1>

<table>
  <thead>
    <tr>
      <th>Ip</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ips.each do |ip| %>
      <tr>
        <td><%= ip.ip %></td>
        <td><%= ip.country %></td>
        <td><%= link_to 'Show', ip %></td>
        <td><%= link_to 'Edit', edit_ip_path(ip) %></td>
        <td><%= link_to 'Destroy', ip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ip', new_ip_path %>

app/views/ips/new.html.erb
<h1>New Ip</h1>

<%= render 'form', ip: @ip %>

<%= link_to 'Back', ips_path %>

app/views/ips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ip:</strong>
  <%= @ip.ip %>
</p>

<p>
  <strong>Country:</strong>
  <%= @ip.country %>
</p>

<%= link_to 'Edit', edit_ip_path(@ip) %> |
<%= link_to 'Back', ips_path %>

app/views/ips/stat.html.erb
<p id="notice"><%= notice %></p>

<h1>Stats</h1>

<table>
  <thead>
    <tr>
      <th>Country</th>
      <th>count</th>
    </tr>
  </thead>

  <tbody>
    <% @stat.each do |st| %>
      <tr>
        <td><%= st[0] %></td>
        <td><%= st[1] %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paylertest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>